### ISSUE TITLE
I am INADEQUATE

### ISSUE THREAD

**Issue by Rairee** [pawelgrzybek/pawelgrzybek#3]
I don't think my brain will ever absorb the knowledge provided to ever figure out what in the hell I'm supposed/not supposed to do here. I feel incredibly stupid and lost.  I need to acquire the manual/book that's titled 
"Coding for the Worlds Biggest Dummy"

**Comment by pawelgrzybek** [comment]
Everyone needs to start somewhere. I felt the same 10 years ago. I will be happy to help you with whatever you need help with, just let me know @Rairee :)
